version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
